# Generated by Django 5.0.2 on 2024-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
