# Generated by Django 4.2.4 on 2023-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='{% static assets %}')),
            ],
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='pub_date',
        ),
    ]
