# Generated by Django 4.2.4 on 2023-10-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_randomimg_remove_prayer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomimg',
            name='img',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
