# Generated by Django 4.2.7 on 2023-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_randomimg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomimg',
            name='img',
        ),
        migrations.AddField(
            model_name='randomimg',
            name='img_url',
            field=models.CharField(default='assets/jerusalem.png', max_length=200),
        ),
    ]
