# Generated by Django 4.2.7 on 2023-12-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_randomimg_img_randomimg_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomimg',
            name='img_url',
        ),
    ]
