# Generated by Django 4.2.7 on 2023-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_randomimg_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomimg',
            name='img_url',
            field=models.ImageField(default='assets/jerusalem.png', upload_to='assets/'),
            preserve_default=False,
        ),
    ]
