# Generated by Django 4.2.4 on 2024-01-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_intention_type_of_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriquesYS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubriqueName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='intention',
            name='intention_title',
            field=models.CharField(default='YourDefaultValue', max_length=70),
        ),
    ]
